.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. capricoinplus_qt test_capricoinplus_qt
clean: FORCE
	$(MAKE) -C .. capricoinplus_qt_clean test_capricoinplus_qt_clean
check: FORCE
	$(MAKE) -C .. test_capricoinplus_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. capricoinplus_qt
